export default {
  INITREADY: "INITREADY", //未达到队列
  RUN: "RUN", //运行队列
  STATIC_READY: "STATIC_READY", //静止就绪
  ACTIVITY_READY: "ACTIVITY_READY", //活动就绪
  STATIC_BLOCK: "STATIC_BLOCK", //静止阻塞
  ACTIVITY_BLOCK: "ACTIVITY_BLOCK", //活动阻塞
  FINISH: "FINISH" //完成
};
